/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons -fwide-types`
 */

#include "HighFrequencyContainer.h"

static asn_TYPE_member_t asn_MBR_HighFrequencyContainer_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HighFrequencyContainer, choice.basicVehicleContainerHighFrequency),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BasicVehicleContainerHighFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"basicVehicleContainerHighFrequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HighFrequencyContainer, choice.rsuContainerHighFrequency),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSUContainerHighFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rsuContainerHighFrequency"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HighFrequencyContainer, choice.vruContainerHighFrequency),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VRUContainerHighFrequency,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"vruContainerHighFrequency"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_HighFrequencyContainer_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* basicVehicleContainerHighFrequency */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rsuContainerHighFrequency */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* vruContainerHighFrequency */
};
static asn_CHOICE_specifics_t asn_SPC_HighFrequencyContainer_specs_1 = {
	sizeof(struct HighFrequencyContainer),
	offsetof(struct HighFrequencyContainer, _asn_ctx),
	offsetof(struct HighFrequencyContainer, present),
	sizeof(((struct HighFrequencyContainer *)0)->present),
	asn_MAP_HighFrequencyContainer_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_HighFrequencyContainer = {
	"HighFrequencyContainer",
	"HighFrequencyContainer",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_HighFrequencyContainer_1,
	3,	/* Elements count */
	&asn_SPC_HighFrequencyContainer_specs_1	/* Additional specs */
};

