/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "module.asn1"
 * 	`asn1c -S/skeletons -fwide-types`
 */

#ifndef	_VRUContainerHighFrequency_H_
#define	_VRUContainerHighFrequency_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Heading.h"
#include "Speed.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VRUContainerHighFrequency */
typedef struct VRUContainerHighFrequency {
	Heading_t	 heading;
	Speed_t	 speed;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VRUContainerHighFrequency_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VRUContainerHighFrequency;

#ifdef __cplusplus
}
#endif

#endif	/* _VRUContainerHighFrequency_H_ */
#include <asn_internal.h>
